services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://php2692004:LnTuvPmwUWmRCU6y@vincent.juveo.mongodb.net/ManGolden?retryWrites=true&w=majority&appName=Vincent

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
